name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: OpenActuarial/.github/.github/workflows/reusable-ci.yml@main
    with:
      package: risksim
